# Copyright (C) 2019-2020 Siodb GmbH. All rights reserved.
# Use of this source code is governed by a license that can be found
# in the LICENSE file.

# Recursive makefile for Siodb extra files

include ../mk/Prolog.mk
include $(MK)/MainTargets.mk

# List of all subdirs to recurse into
SUBDIRS:= \
	gdbinit  \
	run_all_tests

include $(MK)/ParallelRecurse.mk
