catch throw std::bad_alloc
catch throw std::bad_cast
catch throw std::bad_weak_ptr
catch throw std::invalid_argument
catch throw std::out_of_range
catch throw std::runtime_error
catch throw siodb::iomgr::dbengine::DatabaseError
catch throw siodb::iomgr::dbengine::DatabaseIOError
catch throw siodb::iomgr::dbengine::InternalDatabaseError
catch throw siodb::iomgr::dbengine::UserVisibleDatabaseError
