# Copyright (C) 2019-2020 Siodb GmbH. All rights reserved.
# Use of this source code is governed by a license that can be found
# in the LICENSE file.

# Makefile for the iomgr library "shared"

SRC_DIR:=$(dir $(realpath $(firstword $(MAKEFILE_LIST))))
include ../../../../../mk/Prolog.mk

TARGET_LIB:=siodb_iomgr_shared

CXX_HDR:= \
	IOManagerExitCode.h

C_HDR:=

include $(MK)/Main.mk
