# Copyright (C) 2019-2020 Siodb GmbH. All rights reserved.
# Use of this source code is governed by a license that can be found
# in the LICENSE file.

# rest_server application makefile

SRC_DIR:=$(dir $(realpath $(firstword $(MAKEFILE_LIST))))
include ../mk/Prolog.mk

TARGET_GO_EXE:=siodb_rest_server

GO_SRC:=Main.go

include $(MK)/Main.mk
