CREATE DATABASE TEST_DB1 WITH CIPHER_ID = 'aes128';

CREATE TABLE TEST_DB1.DEPARTMENTS
(
    NAME TEXT
);
INSERT INTO TEST_DB1.DEPARTMENTS
VALUES
    ('Finance');
INSERT INTO TEST_DB1.DEPARTMENTS
VALUES
    ('Information technology');
INSERT INTO TEST_DB1.DEPARTMENTS
VALUES
    ('Marketing');
INSERT INTO TEST_DB1.DEPARTMENTS
VALUES
    ('Human resources');
INSERT INTO TEST_DB1.DEPARTMENTS
VALUES
    ('Sales');

CREATE TABLE TEST_DB1.EMPLOYEES
(
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    SALARY FLOAT,
    HIRE_DATE TIMESTAMP,
    DEPARTMENT_ID INT
);
INSERT INTO TEST_DB1.EMPLOYEES
VALUES
    ('马', '云', 249000.000000, '1964-09-10', 1);
INSERT INTO TEST_DB1.EMPLOYEES
VALUES
    ('Юрий', 'Гагарин', 49000.000000, '1934-03-09', 2);
INSERT INTO TEST_DB1.EMPLOYEES
VALUES
    ('Barack', 'Obama', 149000.000000, '1961-08-04', 4);

